plot:
  spacing:
    ==: cz.minebreak.mico.build_battle.util.Point2D
    x: 7
    y: 7
  size:
    ==: cz.minebreak.mico.build_battle.util.Point3D
    x: 20
    y: 20
    z: 20
  count:
    ==: cz.minebreak.mico.build_battle.util.Point2D
    x: 3
    y: 3
  origin:
    ==: org.bukkit.Location
    world: world
    x: 247.0
    y: 56.0
    z: -90.0
    pitch: 0.0
    yaw: 0.0
min-players: 1
max-players: 9
can-join-during-warmup: false
themes:
  - 'Theme #0'
  - 'Theme #1'
  - 'Theme #2'
  - 'Theme #3'
  - 'Theme #4'
time-theme-voting: 200
time-building: 400
time-build-rating: 400
time-showing-best-build: 400
blacklisted-materials:
  - COMMAND_BLOCK
